#!/usr/bin/env python3
"""Extract symbol addresses from a Merlin32 _Output.txt listing and emit
Merlin32 `equ` declarations.

Usage:
  extract_externs.py <listing.txt> <symbols.txt> <out.s>

`symbols.txt` is a plain-text list of symbol names, one per line. Blank
lines and lines starting with `#` are ignored. The script searches the
listing for the line that *declares* each symbol (i.e. the symbol appears
as the first identifier in the Source column) and writes one
`symbol equ $BB/MMMM` per symbol to `out.s`.
"""
import re
import sys

LINE_RE = re.compile(
    r"^\s*\d+\s*\|\s*\d+\s+\S+\s+\d+\s*\|\s*\S+\s*\|\s*\d+\s*\|"
    r"\s*\|\s*\d+\s*\|\s*([0-9A-Fa-f]{2})/([0-9A-Fa-f]{4})\s*(?::[^|]+)?\|"
    r"\s*(\S+)"
)


def parse_listing(path):
    """Yield (symbol, bank, offset) for every line that starts a label."""
    with open(path, "r") as f:
        for line in f:
            m = LINE_RE.match(line)
            if not m:
                continue
            bank, offset, src_first = m.group(1), m.group(2), m.group(3)
            # Only declarations: first source token must be a bare label
            # (no instruction mnemonic, no directive prefix).
            if src_first.startswith(("*", "]", ":")):
                continue
            # Skip lines whose first token is clearly a mnemonic by checking
            # the line type (Data/Empty are label-declaration types).
            # The regex already isolated the first source token; trust it.
            yield src_first, bank, offset


def main():
    if len(sys.argv) != 4:
        print("usage: extract_externs.py <listing> <symbols.txt> <out.s>",
              file=sys.stderr)
        sys.exit(2)

    listing_path, symbols_path, out_path = sys.argv[1:]

    wanted = set()
    with open(symbols_path) as f:
        for line in f:
            s = line.split("#", 1)[0].strip()
            if s:
                wanted.add(s)

    found = {}
    for sym, bank, off in parse_listing(listing_path):
        if sym in wanted and sym not in found:
            found[sym] = (bank, off)

    missing = sorted(wanted - found.keys())
    if missing:
        print(f"extract_externs.py: missing symbols: {missing}",
              file=sys.stderr)
        sys.exit(1)

    with open(out_path, "w") as f:
        f.write("* Auto-generated by tools/extract_externs.py — do not edit.\n")
        f.write("* Bank-$00 symbol addresses imported from game.s listing.\n")
        for sym in sorted(found):
            bank, off = found[sym]
            f.write(f"{sym:32s} equ ${bank}{off}\n")


if __name__ == "__main__":
    main()
