#!/usr/bin/env python3
"""Extract symbol addresses from a Merlin32 _Output.txt listing and emit
Merlin32 `equ` declarations.

Usage:
  extract_externs.py <listing.txt> <symbols.txt> <out.s>

`symbols.txt` is a plain-text list of symbol names, one per line. Blank
lines and lines starting with `#` are ignored. The script searches the
listing for the line that *declares* each symbol (i.e. the symbol appears
as the first identifier in the Source column) and writes one
`symbol equ $BB/MMMM` per symbol to `out.s`.
"""
import re
import sys

LINE_RE = re.compile(
    r"^\s*\d+\s*\|\s*\d+\s+\S+\s+\d+\s*\|\s*(\S+)\s*\|\s*\d+\s*\|"
    r"\s*\|\s*\d+\s*\|\s*([0-9A-Fa-f]{2})/([0-9A-Fa-f]{4})\s*(?::[^|]+)?\|"
    r"\s*(.*)$"
)

EQU_VALUE_RE = re.compile(
    r"^([a-zA-Z_][a-zA-Z0-9_]*)\s+(=|equ)\s+(\S+)"
)


def parse_listing(path):
    """Yield (symbol, kind, value).

    kind is 'addr' for normal data/code labels (bank/offset is the
    address), or 'equ' for symbols defined via `name = value` /
    `name equ value` (we copy the value verbatim).
    """
    with open(path, "r") as f:
        for line in f:
            m = LINE_RE.match(line)
            if not m:
                continue
            line_type, bank, offset, source = m.groups()
            src_stripped = source.strip()
            if not src_stripped or src_stripped.startswith(("*", "]", ":")):
                continue
            tokens = src_stripped.split()
            sym = tokens[0]
            if line_type == "Equivalence":
                em = EQU_VALUE_RE.match(src_stripped)
                if em:
                    yield em.group(1), "equ", em.group(3)
                continue
            # Address-type binding (Empty / Code / Data lines that
            # *start* with a label).
            if not sym[0].isalpha() and sym[0] != "_":
                continue
            yield sym, "addr", f"${bank}{offset}"


def main():
    if len(sys.argv) != 4:
        print("usage: extract_externs.py <listing> <symbols.txt> <out.s>",
              file=sys.stderr)
        sys.exit(2)

    listing_path, symbols_path, out_path = sys.argv[1:]

    wanted = set()
    with open(symbols_path) as f:
        for line in f:
            s = line.split("#", 1)[0].strip()
            if s:
                wanted.add(s)

    found = {}
    for sym, kind, value in parse_listing(listing_path):
        if sym in wanted and sym not in found:
            found[sym] = (kind, value)

    missing = sorted(wanted - found.keys())
    if missing:
        print(f"extract_externs.py: missing symbols: {missing}",
              file=sys.stderr)
        sys.exit(1)

    with open(out_path, "w") as f:
        f.write("* Auto-generated by tools/extract_externs.py — do not edit.\n")
        f.write("* Bank-$00 symbol addresses imported from game.s listing.\n")
        for sym in sorted(found):
            kind, value = found[sym]
            f.write(f"{sym:32s} equ {value}\n")


if __name__ == "__main__":
    main()
