#!/usr/bin/env python3
"""Rewrite engine.s so its scratch data lives in bank $00.

The naive migration left local labels like `:fsg_off` and globals like
`push_ymin` declared inside engine.s (so they live at $1F:nnnn) but
accessed via 16-bit absolute mode (which uses DBR=$00 → reads garbage
from bank $00). Fix: move every engine.s-internal storage cell into
bank $00 by:

  1. Deleting the storage declarations from engine.s.
  2. Renaming every reference from `:fsg_off` to `fsg_off` so the
     symbol is global (not scope-bound to engine.s's labels).
  3. Emitting a companion `engine_data.s` block to PUT into game.s,
     which redeclares the same labels at bank-$00 addresses with the
     same widths.

`engine_externs.s` (regenerated by extract_externs.py) picks up the
bank-$00 addresses on the next game.s build.
"""
import re
import sys

# (label-name-without-colon, ds-size-in-bytes, init-form). The init-form
# is the directive we'll emit in engine_data.s (preserves the original
# declaration's intent: `ds N` for uninitialised scratch, `dfb N` for
# byte-init, `dw N` for word-init).
PRIVATE_DATA = [
    # scroll_right scratch (fill_split_general)
    ("fsg_off",            "ds 1"),
    ("fsg_count1",         "ds 1"),
    ("fsg_count2",         "ds 1"),
    ("fsg_curr",           "ds 1"),
    # scroll_left scratch
    ("old_lo",             "dfb 0"),
    ("nfp",                "dfb 0"),
    ("nfc",                "dfb 0"),
    ("prev_start",         "dfb 0"),
    ("rg1_count",          "dw 0"),
    ("rg2_count",          "dw 0"),
    # scroll_up scratch
    ("ufill_top",          "ds 2"),
    ("utmp",               "ds 2"),
    ("rgap_start",         "ds 2"),
    ("rgap_count",         "ds 2"),
    ("lgap_base",          "ds 2"),
    ("dl_wx",              "ds 2"),
    ("dl_cnt",             "ds 1"),
    ("ldr_ctr",            "ds 2"),
    ("lower_rgap_count",   "ds 2"),
    ("snap_lo_s9_count",   "ds 2"),
    ("ffs_count",          "ds 2"),
    ("ffs_dst",            "ds 2"),
    ("ffs_s9_count",       "ds 2"),
    ("snap_wo_delta",      "ds 2"),
    # push_band scratch
    ("pb_save_s",          "ds 2"),
    ("pb_tmp",             "ds 2"),
    # compute_up_align / scroll_up shared inputs (previously plain globals
    # in engine.s — same hazard, fix the same way).
    ("up_src_start",       "ds 2"),
    ("up_dst_start",       "ds 2"),
    ("up_count",           "ds 2"),
    ("push_ymin",          "dfb 0"),
    ("push_ymax",          "dfb 0"),
]

LOCAL_NAMES = {name for name, _ in PRIVATE_DATA if name not in
               {"up_src_start", "up_dst_start", "up_count",
                "push_ymin", "push_ymax"}}
GLOBAL_NAMES = {name for name, _ in PRIVATE_DATA if name in
                {"up_src_start", "up_dst_start", "up_count",
                 "push_ymin", "push_ymax"}}


def rewrite_engine(in_path, out_path):
    out_lines = []
    with open(in_path) as f:
        for line in f:
            stripped = line.rstrip("\n")
            # 1) Drop the declaration line (matches :name OR name then
            #    a storage directive).
            decl_m = re.match(
                r"^:?([a-z_][a-zA-Z0-9_]*)\s+(ds|dfb|dw|hex)\b", stripped)
            if decl_m and decl_m.group(1) in (LOCAL_NAMES | GLOBAL_NAMES):
                continue
            # 2) Strip leading `:` from references to the local-name set.
            #    Match `<mnemonic> :name` and `:name` standalone (e.g. as
            #    operand of a long-pointer indexed mode). We only touch
            #    occurrences that show up in operand positions, never
            #    inside comments or string literals.
            def sub_ref(m):
                name = m.group(1)
                if name in LOCAL_NAMES:
                    return name
                return m.group(0)
            # Operand-only replacement: a `:label` token preceded by
            # whitespace or `(` (for indirect addressing), followed by
            # end-of-token (whitespace, comma, ), end-of-line).
            stripped = re.sub(
                r"(?<=[\s(,])"
                r":([a-z_][a-zA-Z0-9_]*)"
                r"(?=$|[\s,)])",
                sub_ref, stripped)
            out_lines.append(stripped)
    with open(out_path, "w") as f:
        f.write("\n".join(out_lines))
        if not out_lines or not out_lines[-1].endswith("\n"):
            f.write("\n")


def write_engine_data(path):
    with open(path, "w") as f:
        f.write("*----------------------------------------------------------\n")
        f.write("* engine_data.s — bank-$00 scratch storage for engine.s.\n")
        f.write("*\n")
        f.write("* engine.s lives in bank $1F but runs with DBR=$00, so its\n")
        f.write("* private scratch cells must live in bank $00 too. They're\n")
        f.write("* declared here, PUT into game.s, and re-equ'd into engine.s\n")
        f.write("* by engine_externs.s (via tools/extract_externs.py).\n")
        f.write("*----------------------------------------------------------\n")
        for name, init in PRIVATE_DATA:
            f.write(f"{name:24s} {init}\n")


def main():
    if len(sys.argv) != 4:
        print("usage: fix_engine_data.py <engine.s in> <engine.s out> "
              "<engine_data.s out>",
              file=sys.stderr)
        sys.exit(2)
    rewrite_engine(sys.argv[1], sys.argv[2])
    write_engine_data(sys.argv[3])


if __name__ == "__main__":
    main()
