**********************************************************************
* mission1_strata.s — generated by tools/gen_strata.py
* DO NOT EDIT. Inputs:
*   tools/mission2_strata.txt
*   src/mission2.s
*
* Per-row world-coord bounds tables. Index by world_y (0..199).
* Each row: 2 spans × (16-bit bmin, 16-bit bmax) = 8 bytes total.
* Layout: dw span1_bmin, span1_bmax, span2_bmin, span2_bmax.
* Walkable iff (bmin <= world_x <= bmax) for either span.
* Unused-span sentinel: bmin=$FFFF, bmax=$0000 (impossible range).
**********************************************************************

screen_to_stratum
 dfb $00                  ; scr0
 dfb $00                  ; scr1
 dfb $00                  ; scr2
 dfb $00                  ; scr3
 dfb $00                  ; scr4
 dfb $00                  ; scr5
 dfb $00                  ; scr6
 dfb $00                  ; scr7
 dfb $00                  ; scr8
 dfb $00                  ; scr9

strata_index
 dw stratum_ground

stratum_ground
 dw $FFFF,$0000,$FFFF,$0000        ; y=  0  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  1  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  2  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  3  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  4  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  5  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  6  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  7  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  8  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=  9  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 10  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 11  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 12  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 13  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 14  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 15  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 16  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 17  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 18  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 19  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 20  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 21  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 22  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 23  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 24  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 25  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 26  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 27  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 28  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 29  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 30  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 31  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 32  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 33  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 34  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 35  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 36  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 37  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 38  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 39  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 40  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 41  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 42  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 43  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 44  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 45  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 46  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 47  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 48  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 49  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 50  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 51  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 52  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 53  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 54  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 55  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 56  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 57  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 58  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 59  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 60  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 61  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 62  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 63  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 64  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 65  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 66  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 67  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 68  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 69  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 70  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 71  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 72  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 73  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 74  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 75  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 76  blocked
 dw $0000,$0095,$FFFF,$0000        ; y= 77  [0..149]
 dw $FFFF,$0000,$FFFF,$0000        ; y= 78  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 79  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 80  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 81  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 82  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 83  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 84  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 85  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 86  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 87  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 88  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 89  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 90  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 91  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 92  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 93  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 94  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 95  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 96  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 97  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 98  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y= 99  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=100  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=101  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=102  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=103  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=104  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=105  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=106  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=107  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=108  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=109  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=110  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=111  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=112  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=113  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=114  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=115  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=116  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=117  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=118  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=119  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=120  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=121  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=122  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=123  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=124  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=125  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=126  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=127  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=128  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=129  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=130  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=131  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=132  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=133  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=134  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=135  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=136  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=137  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=138  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=139  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=140  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=141  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=142  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=143  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=144  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=145  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=146  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=147  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=148  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=149  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=150  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=151  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=152  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=153  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=154  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=155  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=156  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=157  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=158  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=159  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=160  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=161  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=162  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=163  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=164  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=165  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=166  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=167  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=168  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=169  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=170  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=171  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=172  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=173  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=174  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=175  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=176  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=177  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=178  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=179  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=180  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=181  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=182  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=183  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=184  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=185  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=186  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=187  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=188  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=189  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=190  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=191  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=192  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=193  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=194  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=195  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=196  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=197  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=198  blocked
 dw $FFFF,$0000,$FFFF,$0000        ; y=199  blocked

